server:
  port: 1316

spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:radata.db

#showSql
logging:
  level:
    com.github.hieheihei.hdog: debug
  file:
    name: RALiteWebBackend.log